alter table "public"."comments" drop constraint "comments_profile_id_fkey";
alter table "public"."event_inputs" drop constraint "event_inputs_input_id_fkey";
alter table "public"."event_inputs" drop constraint "event_inputs_input_option_id_fkey";
alter table "public"."event_type_inputs" drop constraint "event_type_inputs_event_type_id_fkey";
alter table "public"."event_type_inputs" drop constraint "event_type_inputs_input_id_fkey";
alter table "public"."event_types" drop constraint "event_types_session_id_fkey";
alter table "public"."event_types" drop constraint "event_types_subject_id_fkey";
alter table "public"."events" drop constraint "events_event_type_id_fkey";
alter table "public"."events" drop constraint "events_profile_id_fkey";
alter table "public"."events" drop constraint "events_subject_id_fkey";
alter table "public"."input_options" drop constraint "input_options_input_id_fkey";
alter table "public"."input_subjects" drop constraint "input_subjects_input_id_fkey";
alter table "public"."input_subjects" drop constraint "input_subjects_subject_id_fkey";
alter table "public"."inputs" drop constraint "inputs_team_id_fkey";
alter table "public"."missions" drop constraint "missions_subject_id_fkey";
alter table "public"."sessions" drop constraint "sessions_mission_id_fkey";
alter table "public"."subject_managers" drop constraint "subject_managers_subject_id_fkey";
alter table "public"."subjects" drop constraint "subjects_team_id_fkey";
alter table "public"."team_members" drop constraint "team_members_team_id_fkey";
alter table "public"."templates" drop constraint "templates_team_id_fkey";
alter table "public"."comments" add constraint "comments_profile_id_fkey" FOREIGN KEY (profile_id) REFERENCES profiles(id) ON DELETE CASCADE not valid;
alter table "public"."comments" validate constraint "comments_profile_id_fkey";
alter table "public"."event_inputs" add constraint "event_inputs_input_id_fkey" FOREIGN KEY (input_id) REFERENCES inputs(id) ON DELETE CASCADE not valid;
alter table "public"."event_inputs" validate constraint "event_inputs_input_id_fkey";
alter table "public"."event_inputs" add constraint "event_inputs_input_option_id_fkey" FOREIGN KEY (input_option_id) REFERENCES input_options(id) ON DELETE CASCADE not valid;
alter table "public"."event_inputs" validate constraint "event_inputs_input_option_id_fkey";
alter table "public"."event_type_inputs" add constraint "event_type_inputs_event_type_id_fkey" FOREIGN KEY (event_type_id) REFERENCES event_types(id) ON DELETE CASCADE not valid;
alter table "public"."event_type_inputs" validate constraint "event_type_inputs_event_type_id_fkey";
alter table "public"."event_type_inputs" add constraint "event_type_inputs_input_id_fkey" FOREIGN KEY (input_id) REFERENCES inputs(id) ON DELETE CASCADE not valid;
alter table "public"."event_type_inputs" validate constraint "event_type_inputs_input_id_fkey";
alter table "public"."event_types" add constraint "event_types_session_id_fkey" FOREIGN KEY (session_id) REFERENCES sessions(id) ON DELETE CASCADE not valid;
alter table "public"."event_types" validate constraint "event_types_session_id_fkey";
alter table "public"."event_types" add constraint "event_types_subject_id_fkey" FOREIGN KEY (subject_id) REFERENCES subjects(id) ON DELETE CASCADE not valid;
alter table "public"."event_types" validate constraint "event_types_subject_id_fkey";
alter table "public"."events" add constraint "events_event_type_id_fkey" FOREIGN KEY (event_type_id) REFERENCES event_types(id) ON DELETE CASCADE not valid;
alter table "public"."events" validate constraint "events_event_type_id_fkey";
alter table "public"."events" add constraint "events_profile_id_fkey" FOREIGN KEY (profile_id) REFERENCES profiles(id) ON DELETE CASCADE not valid;
alter table "public"."events" validate constraint "events_profile_id_fkey";
alter table "public"."events" add constraint "events_subject_id_fkey" FOREIGN KEY (subject_id) REFERENCES subjects(id) ON DELETE CASCADE not valid;
alter table "public"."events" validate constraint "events_subject_id_fkey";
alter table "public"."input_options" add constraint "input_options_input_id_fkey" FOREIGN KEY (input_id) REFERENCES inputs(id) ON DELETE CASCADE not valid;
alter table "public"."input_options" validate constraint "input_options_input_id_fkey";
alter table "public"."input_subjects" add constraint "input_subjects_input_id_fkey" FOREIGN KEY (input_id) REFERENCES inputs(id) ON DELETE CASCADE not valid;
alter table "public"."input_subjects" validate constraint "input_subjects_input_id_fkey";
alter table "public"."input_subjects" add constraint "input_subjects_subject_id_fkey" FOREIGN KEY (subject_id) REFERENCES subjects(id) ON DELETE CASCADE not valid;
alter table "public"."input_subjects" validate constraint "input_subjects_subject_id_fkey";
alter table "public"."inputs" add constraint "inputs_team_id_fkey" FOREIGN KEY (team_id) REFERENCES teams(id) ON DELETE CASCADE not valid;
alter table "public"."inputs" validate constraint "inputs_team_id_fkey";
alter table "public"."missions" add constraint "missions_subject_id_fkey" FOREIGN KEY (subject_id) REFERENCES subjects(id) ON DELETE CASCADE not valid;
alter table "public"."missions" validate constraint "missions_subject_id_fkey";
alter table "public"."sessions" add constraint "sessions_mission_id_fkey" FOREIGN KEY (mission_id) REFERENCES missions(id) ON DELETE CASCADE not valid;
alter table "public"."sessions" validate constraint "sessions_mission_id_fkey";
alter table "public"."subject_managers" add constraint "subject_managers_subject_id_fkey" FOREIGN KEY (subject_id) REFERENCES subjects(id) ON DELETE CASCADE not valid;
alter table "public"."subject_managers" validate constraint "subject_managers_subject_id_fkey";
alter table "public"."subjects" add constraint "subjects_team_id_fkey" FOREIGN KEY (team_id) REFERENCES teams(id) ON DELETE CASCADE not valid;
alter table "public"."subjects" validate constraint "subjects_team_id_fkey";
alter table "public"."team_members" add constraint "team_members_team_id_fkey" FOREIGN KEY (team_id) REFERENCES teams(id) ON DELETE CASCADE not valid;
alter table "public"."team_members" validate constraint "team_members_team_id_fkey";
alter table "public"."templates" add constraint "templates_team_id_fkey" FOREIGN KEY (team_id) REFERENCES teams(id) ON DELETE CASCADE not valid;
alter table "public"."templates" validate constraint "templates_team_id_fkey";
