name: Preview
on:
  push:
    branches-ignore:
      - main
env:
  NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
  NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
  SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
  SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}
  SUPABASE_PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID }}
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
jobs:
  Deploy:
    runs-on: ubuntu-latest
    environment: Preview
    steps:
      - uses: actions/checkout@v3
      - run: npm i
      - run: npx vercel pull --yes --environment=preview --token="$VERCEL_TOKEN"
      - run: npx supabase link --project-ref "$SUPABASE_PROJECT_ID"
      - run: npm run db:start
      - run: npm run db:types
      - run: npx vercel build
      - run: npx supabase db push
      - run: npx vercel deploy --prebuilt --token="$VERCEL_TOKEN"
