name: Preview
on:
  push:
    branches-ignore:
      - main
env:
  NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
  NEXT_PUBLIC_SUPABASE_PRO: ${{ secrets.NEXT_PUBLIC_SUPABASE_PRO }}
  NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
  SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
  SUPABASE_DB_PASSWORD_INLINE: ${{ secrets.SUPABASE_DB_PASSWORD }}
  SUPABASE_PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID }}
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
jobs:
  Deploy:
    runs-on: ubuntu-latest
    environment: Preview
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - run: bun i
      - run: bun vercel pull -y --environment=preview --token="$VERCEL_TOKEN"
      - run: bun supabase link --project-ref "$SUPABASE_PROJECT_ID"
      - run: bun db:start
      - run: bun db:types
      - run: bun next telemetry disable
      - run: bun vercel build
      - run: bun supabase db push --password "$SUPABASE_DB_PASSWORD_INLINE"
      - run: bun vercel deploy --prebuilt --token="$VERCEL_TOKEN"
