name: Production
on:
  push:
    branches:
      - main
env:
  NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
  NEXT_PUBLIC_SUPABASE_PRO: ${{ secrets.NEXT_PUBLIC_SUPABASE_PRO }}
  NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
  SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
  SUPABASE_DB_PASSWORD_INLINE: ${{ secrets.SUPABASE_DB_PASSWORD }}
  SUPABASE_PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID }}
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
jobs:
  Deploy:
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
      - run: pnpm i
      - run:
          pnpm exec vercel pull --yes --environment=production
          --token="$VERCEL_TOKEN"
      - run: pnpm exec supabase link --project-ref "$SUPABASE_PROJECT_ID"
      - run: pnpm run db:start
      - run: pnpm run db:types
      - run: pnpm exec next telemetry disable
      - run: pnpm exec vercel build --prod
      - run:
          pnpm exec supabase db push --password "$SUPABASE_DB_PASSWORD_INLINE"
      - run: pnpm exec vercel deploy --prebuilt --prod --token="$VERCEL_TOKEN"
