name: Production
on:
  push:
    branches:
      - main
env:
  NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
  NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
  SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
jobs:
  Deploy:
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - run: bun i
      - run: bun vercel pull -y --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      - run: bun supabase link --project-ref ${{ secrets.SUPABASE_PROJECT_ID }}
      - run: bun db:start
      - run: bun db:types
      - run: bun next telemetry disable
      - run: bun vercel build --prod
      - run: bun supabase db push --password ${{ secrets.SUPABASE_DB_PASSWORD }}
      - run: bun vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
